export const FETCH_CARDS = "FETCH_CARDS";
export const FETCH_CUSTOM_FIELDS = "FETCH_CUSTOM_FIELDS";
export const FETCH_BOARDS_NAME = "FETCH_BOARDS_NAME";
export const FETCH_LISTS_NAME = "FETCH_LISTS_NAME";
